services:
  shortify:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app_network
    depends_on:
      - redis
    volumes:
      - /etc/letsencrypt/live/shortify.ininetech.com.br:/app
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network
    command: ["redis-server", "--appendonly", "no"]

volumes:
  redis_data:
    driver: local

networks:
  app_network:
    driver: bridge